### ISSUE TITLE
Automatically Compiled Binaries?

### ISSUE THREAD

**Issue by LukePrior** [dbdexter-dev/sdrpp_radiosonde#2]
Hi,

I was wondering if you had considered setting up GitHub Actions to automatically generate binaries when you update the plugin.

This would solve the problem of having to manually build SDR++ and could make the plugin much more accessible.

**Comment by SA7BNT** [comment]
Locking for some one who will share a Windows Version from this plugin. 
Im not so confirm to compile it into a exe

**Comment by dbdexter-dev** [comment]
Okay, I think I got GitHub Actions figured out enough to build the plugin automatically. Windows and Linux x86_64 builds are now available [in the Releases page](https://github.com/dbdexter-dev/sdrpp_radiosonde/releases), and installation instructions can be found in the README. Thanks for the suggestion!

Since the plugin doesn't depend on any external libraries, the Linux build should work across all distributions. If that's not the case, feel free to let me know.

**Comment by LukePrior** [comment]
Perfect thanks.
